server:
  servlet:
    context-path: /
  port: 8080
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.70.65:3306/appm2?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: btc_user
      password: PpEZqboiBp

  redis:
    host: 192.168.70.59
    port: 6379
    password: space520
    timeout: 3000
    jedis:
      pool:
        max-active: 50
        min-idle: 10
        max-idle: 20
        max-wait: -1

  rabbitmq:
    host: 192.168.70.79
    port: 5673
    username: ikongjian
    password: 5pK29Jab8ujvytBc

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    health:
      show-details: always  # 显示健康详情
